### ISSUE TITLE
Moving to an organization

### ISSUE THREAD

**Issue by m1guelpf** [laravel-frontend-presets/uikit3#1]
Hi!
What do you think about moving this an other packages like this to an organization, like the community did with the notification channels?

**Comment by OwenMelbz** [comment]
You'd need to enlighten me with what happened with notifications :D but please do give your idea of what you have got in mind, I'm sure something can be done :)

**Comment by m1guelpf** [comment]
When custom notifications channels were released, the Laravel community made a GitHub organization for grouping them. They did the same for custom socialite providers

**Comment by OwenMelbz** [comment]
Okay cool, yeah thats sounds good.

I'd setup a free organisation, and transferred ownership so its now at https://github.com/laravel-frontent-presets/uikit3-preset

What else would you suggest needs to happen?

**Comment by m1guelpf** [comment]
Hi again!
I want to start adding more templates.
Could you invite me to the organization & give me permission to create repos?
Thank you!

**Comment by OwenMelbz** [comment]
All working??? :D
