### ISSUE TITLE
Beta 35, deprecating jquery and passport scaffolds

### ISSUE THREAD

**Issue by mohamedhamad** [laravel-frontend-presets/uikit3#11]
Hey guys, pretty excited about this and using it on a new project I’m working on.
Any plans for updating to the latest beta, removing the jquery dependency and creating views for Laravel passport?

**Comment by cesaramirez** [comment]
Hi @mohamedhamad you can use this repo https://github.com/twoquethree/laravel-uikit, it is updated with the latest version of uikit.

**Comment by cesaramirez** [comment]
@OwenMelbz Why do I delete my comment?

**Comment by OwenMelbz** [comment]
@mohamedhamad I've updated it to the latest uikit beta.

However what exactly do you mean by passport scaffolds?

**Comment by mohamedhamad** [comment]
Laravel passport has a couple of vue js components that are bootstrap based. I was wondering if presets work with all the other Laravel components too

**Comment by mohamedhamad** [comment]
And thanks for updating to the latest version! Looking forward to using UIKit in my project
