### ISSUE TITLE
Essential .js not included - basic stuff does not work

### ISSUE THREAD

**Issue by andreasba** [laravel-frontend-presets/uikit3#12]
Hi there

thanks for the great scaffolding - however, I spent an entire evening wondering why basis things like cards or grids did not work, only to found out that the most basic thing was not done: 

require('./uikit');
require('./uikit-icons');

were missing in the app.js, so no wonder nothing worked!

Maybe it would be a good idea to include that in the build or document it somehow!?

Thanks
Andreas

**Comment by OwenMelbz** [comment]
Hi @andreasba 

It should do this.

You can see here in the code

https://github.com/laravel-frontend-presets/uikit3/blob/master/src/UIKit3Preset.php#L76

It replaces the bootstrap sass with uikit.

By any chance had you manually removed bootstrap first or something?

**Comment by andreasba** [comment]
Hi @OwenMelbz - I had Bootstrap installed and had a bit of a rough time to get rid of it yes, so I might have done such thing. If this works per default, it certainly was my error so I close the issue - thanks for your quick reply :)
