### ISSUE TITLE
ERROR in ./resources/assets/js/bootstrap.js

### ISSUE THREAD

**Issue by Philword** [laravel-frontend-presets/uikit3#13]
Hi, just installed it with auth presets and my npm shows me this: 

ERROR in ./resources/assets/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/phillipkishkovrov/Sites/mail/resources/assets/js'
 @ ./resources/assets/js/bootstrap.js 3:16-36
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

Dropdown in presets also does't work. 

How to fix it? 

Thank you!

**Comment by OwenMelbz** [comment]
Hi,

Popper.js is not a part of uikit, so this must be coming from something else that’s been added.

Have you got a popper.js in your package.json ?

Have you done an npm install?

Have you looked at what code is trying to import popper?

**Comment by OwenMelbz** [comment]
I'm going to close this as it seems unrelated and no response
