### ISSUE TITLE
uikit-rtl instead uikit

### ISSUE THREAD

**Issue by zymawy** [laravel-frontend-presets/uikit3#14]
Hi Thank you for the hard work 🔥 

I'm trying to replace uikit css with uikit-rtl How I Can achieve that?

**Comment by OwenMelbz** [comment]
Hi @zymawy - technically this package just removes bootstrap and then includes uikit.

This means you get a normal install of uikit ready to do what ever you need.

You'll then need to follow the uikit docs to change it which is described https://getuikit.com/docs/rtl

As this is out of the remit of this package and is a uikit configuration not laravel I'll close this
