### ISSUE TITLE
Why i can't use uikit icon

### ISSUE THREAD

**Issue by UnclePluto** [laravel-frontend-presets/uikit3#15]
i can't use icon like the UIKIt Documentation said.

I only can use a little icon in app.js, if l include the 
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.42/js/uikit-icons.min.js"></script>
than i can use the icon.

is there some component i didn't include?

**Comment by OwenMelbz** [comment]
Hi @UnclePluto - what error are you getting?

**Comment by UnclePluto** [comment]
thanks i figure it out, i am not good at frontend. it is just some basic knowledge of frontend

**Comment by dberry37388** [comment]
Sorry for commenting on a closed ticket, but @UnclePluto how did you resolve the issue? I am facing the same problem.
