### ISSUE TITLE
Home view missing logout link

### ISSUE THREAD

**Issue by nille** [laravel-frontend-presets/uikit3#8]
When I'm logged in and in the home view I can only see my name. There is no drop-down link (or other alternative) to logout.

Nice project btw!

**Comment by m1guelpf** [comment]
ping @laravel-frontend-presets/uikit-preset

**Comment by nille** [comment]
Not sure what that means?

**Comment by nille** [comment]
Never mind. Fixed it by adding a jquery include to app.blade.php.

**Comment by nille** [comment]
But perhaps there still is a problem? Looks to me like bootstrap.js includes jquery so I probably shouldn't have to link it manually?

**Comment by OwenMelbz** [comment]
@nille have you run mix to compile the assets?

**Comment by nille** [comment]
@OwenMelbz Yes, I have. 
Also, if I inspect the page in chromes console I see this error:

bootstrap.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.

Not sure why there is a reference to Bootstrap there.

**Comment by OwenMelbz** [comment]
Can you paste your bootstrap.js and your package.json? Ideally within the x3 ``` so it looks like

```js
{ blah }
```

**Comment by nille** [comment]
I'm ashamed to admit it but the fault was (off course) my own. Apparently one of my chrome addons messed everything up as it has some sort of reference to bootstrap/jquery. 
(Here is the addon in case you are interested: https://chrome.google.com/webstore/detail/whatshisface/hdlljjddnhidfgllahkjhpfgommecolc?hl=en-GB)

Thanks!!

**Comment by zymawy** [comment]
You can just import the uikit in app.js


```javascript
import UIkit from "uikit";
import Icons from "uikit/dist/js/uikit-icons";

// loads the Icon plugin
UIkit.use(Icons);

// components can be called from the imported UIkit reference
UIkit.notification("Hello world.");
```
